import Link from "next/link";
import { fetchExecutiveKpis, ExecutiveKpi } from "../../services/reporting";

const colors = { background: "#f4f7f8", foreground: "#1a2b32", surface: "#ffffff", sidebar: "#0f3d3e", sidebarMuted: "#9ebdbd", sidebarHover: "#165153", accent: "#1f7a7a", border: "#d5e0e2", muted: "#5c7278" };

function percent(value: number | null): string { return value === null ? "—" : `${(value * 100).toFixed(1)}%`; }
export const dynamic = "force-dynamic";

export default async function ReportingPage() {
  let rows: ExecutiveKpi[] = [];
  let error = "";
  try { rows = await fetchExecutiveKpis(); } catch (cause) { error = cause instanceof Error ? cause.message : "Unable to load reporting data"; }
  const period = rows[0]?.reporting_window_timestamp ? new Date(rows[0].reporting_window_timestamp).toLocaleDateString() : "No completed weekly run";
  const totalVolume = rows.reduce((total, row) => total + (row.network_appointment_volume ?? 0), 0);
  const averageNoShow = rows.length ? rows.reduce((total, row) => total + (row.global_no_show_rate ?? 0), 0) / rows.length : null;
  const averageDenial = rows.length ? rows.reduce((total, row) => total + (row.claims_denial_rate ?? 0), 0) / rows.length : null;
  const navItems = [{ href: "/", label: "Overview" }, { href: "/reporting", label: "Executive reporting" }, { href: "/inventory", label: "Clinic supplies" }];

  return <div style={{ minHeight: "100vh", display: "flex", background: colors.background, color: colors.foreground, fontFamily: "Arial, sans-serif" }}>
    <aside style={{ width: 240, flexShrink: 0, display: "flex", flexDirection: "column", background: colors.sidebar, color: "white" }}>
      <div style={{ padding: "28px 24px", borderBottom: "1px solid rgba(255,255,255,.1)" }}><div style={{ fontFamily: "Georgia, serif", fontSize: 24 }}>HealthCore</div><div style={{ marginTop: 8, color: colors.sidebarMuted, fontSize: 11, textTransform: "uppercase", letterSpacing: ".16em" }}>Internal use only</div></div>
      <nav aria-label="Backoffice navigation" style={{ display: "flex", flex: 1, flexDirection: "column", gap: 5, padding: "20px 12px" }}>{navItems.map((item) => { const active = item.href === "/reporting"; return <Link key={item.href} href={item.href} style={{ display: "block", borderRadius: 6, padding: "11px 13px", color: active ? "white" : colors.sidebarMuted, background: active ? colors.sidebarHover : "transparent", textDecoration: "none", fontSize: 14, fontWeight: active ? 600 : 400 }}>{item.label}</Link>; })}</nav>
      <div style={{ padding: "16px 24px", borderTop: "1px solid rgba(255,255,255,.1)", color: colors.sidebarMuted, fontSize: 11 }}>Staff only · HIPAA / UK GDPR</div>
    </aside>
    <div style={{ minWidth: 0, flex: 1 }}>
      <header style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 24, borderBottom: `1px solid ${colors.border}`, background: colors.surface, padding: "20px 36px" }}><div><div style={{ color: colors.muted, fontSize: 11, fontWeight: 700, letterSpacing: ".14em", textTransform: "uppercase" }}>Operations workspace</div><div style={{ marginTop: 5, fontFamily: "Georgia, serif", fontSize: 22 }}>Executive reporting</div></div><div style={{ textAlign: "right", fontSize: 13 }}><div style={{ fontWeight: 600 }}>Welcome, James Osei</div><div style={{ marginTop: 4, color: colors.muted }}>Austin tech unit</div></div></header>
      <main style={{ maxWidth: 1180, margin: "0 auto", padding: "40px 36px" }}>
        <section style={{ display: "flex", alignItems: "flex-end", justifyContent: "space-between", gap: 24, marginBottom: 32 }}><div><div style={{ color: colors.accent, fontSize: 12, fontWeight: 700, letterSpacing: ".16em", textTransform: "uppercase" }}>Leadership view</div><h1 style={{ margin: "10px 0 8px", fontFamily: "Georgia, serif", fontSize: "clamp(32px, 5vw, 48px)", fontWeight: 400, letterSpacing: "-.03em" }}>Weekly network performance.</h1><p style={{ maxWidth: 650, margin: 0, color: colors.muted, fontSize: 15, lineHeight: 1.7 }}>A concise view of appointment activity, access to care, and financial performance across HealthCore clinics.</p></div><Link href="/" style={{ flexShrink: 0, border: `1px solid ${colors.border}`, borderRadius: 5, background: colors.surface, padding: "11px 16px", color: colors.accent, textDecoration: "none", fontSize: 13, fontWeight: 700 }}>← Back to overview</Link></section>
        {error ? <div role="alert" style={{ marginBottom: 24, border: "1px solid #f0b8b8", borderRadius: 8, background: "#fff5f5", padding: "14px 16px", color: "#8b2525", fontSize: 14 }}>Reporting data unavailable: {error}</div> : null}
        <section aria-label="Reporting summary" style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))", gap: 16, marginBottom: 28 }}>{[{ label: "Reporting period", value: period, note: "Latest completed run" }, { label: "Network appointments", value: totalVolume.toLocaleString(), note: "Across reporting rows" }, { label: "Average no-show rate", value: percent(averageNoShow), note: "Network average" }, { label: "Average denial rate", value: percent(averageDenial), note: "Claims performance" }].map((metric) => <article key={metric.label} style={{ border: `1px solid ${colors.border}`, borderRadius: 8, background: colors.surface, padding: "22px 20px" }}><div style={{ color: colors.muted, fontSize: 11, fontWeight: 700, letterSpacing: ".12em", textTransform: "uppercase" }}>{metric.label}</div><div style={{ marginTop: 13, fontFamily: "Georgia, serif", fontSize: metric.label === "Reporting period" ? 21 : 30 }}>{metric.value}</div><div style={{ marginTop: 6, color: colors.muted, fontSize: 12 }}>{metric.note}</div></article>)}</section>
        <section style={{ border: `1px solid ${colors.border}`, borderRadius: 8, background: colors.surface, overflowX: "auto" }}><div style={{ padding: "24px 24px 18px", borderBottom: `1px solid ${colors.border}` }}><div style={{ color: colors.accent, fontSize: 11, fontWeight: 700, letterSpacing: ".15em", textTransform: "uppercase" }}>Clinic detail</div><h2 style={{ margin: "10px 0 0", fontFamily: "Georgia, serif", fontSize: 27, fontWeight: 400 }}>Performance by location</h2></div><table style={{ borderCollapse: "collapse", width: "100%", minWidth: 760, fontSize: 14 }}><thead><tr style={{ borderBottom: `1px solid ${colors.border}`, color: colors.muted, fontSize: 11, letterSpacing: ".1em", textTransform: "uppercase" }}>{["Clinic", "Region", "Appointments", "No-show rate", "Denial rate", "Net settled"].map((heading) => <th key={heading} style={{ padding: "14px 20px", textAlign: "left" }}>{heading}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={`${row.reporting_window_timestamp}-${row.clinic_location_id}`} style={{ borderBottom: `1px solid ${colors.border}` }}><td style={{ padding: "16px 20px", fontWeight: 600 }}>{row.clinic_location_id}</td><td style={{ padding: "16px 20px", color: colors.muted }}>{row.market_region}</td><td style={{ padding: "16px 20px" }}>{row.network_appointment_volume ?? "—"}</td><td style={{ padding: "16px 20px" }}>{percent(row.global_no_show_rate)}</td><td style={{ padding: "16px 20px" }}>{percent(row.claims_denial_rate)}</td><td style={{ padding: "16px 20px", fontWeight: 600 }}>{row.revenue_net_settled === null ? "—" : `${row.revenue_currency ?? ""} ${row.revenue_net_settled.toFixed(2)}`}</td></tr>) : <tr><td colSpan={6} style={{ padding: "24px 20px", color: colors.muted }}>No completed reporting rows are available.</td></tr>}</tbody></table></section>
      </main>
    </div>
  </div>;
}
